# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

language:
  - swift
osx_image:
  - xcode11

install:
  - gem install xcpretty

jobs:
  include:
    - script: xcodebuild clean build test -workspace Example/MemoryTrickster.xcworkspace -scheme MemoryTrickster-Example -sdk iphonesimulator -destination 'platform=iOS Simulator,OS=12.0,name=iPhone XS' ONLY_ACTIVE_ARCH=NO -enableCodeCoverage YES | xcpretty -c
      after_script: bash <(curl -s https://codecov.io/bash) -J 'MemoryTrickster'  
    - script: pod lib lint --allow-warnings
